spring.application.name=sienep
spring.config.import=optional:file:.env[.properties]

# PostgreSQL - Supabase
spring.datasource.url=jdbc:postgresql://db.jfxdrmkalyhkqjcptcaw.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:sienep-utec-secret-key-must-be-at-least-256-bits-long-change-in-prod}
jwt.expiration=86400000
