-- ============================================================
-- SIENEP – Esquema PostgreSQL COMPLETO
-- Compatible con spring.jpa.hibernate.ddl-auto=validate
--
-- Uso:
--   psql -U <usuario> -d <base> -f src/main/resources/schema.sql
--
-- El DataSeeder (ApplicationRunner) siembra roles, permisos y
-- estructura académica en runtime: NO insertes datos aquí.
--
-- Orden de secciones: de tablas sin dependencias a tablas que
-- referencian las anteriores, para respetar las FKs.
-- ============================================================


-- ============================================================
-- SECCIÓN 1 – Tablas raíz (sin FK salientes)
-- ============================================================

-- Entidad: Ciudad  →  tabla: ciudades
CREATE TABLE ciudades (
    id_ciudad    SERIAL       PRIMARY KEY,
    cod_postal   INTEGER      NOT NULL UNIQUE,
    nombre       VARCHAR(100) NOT NULL,
    departamento VARCHAR(100) NOT NULL
);

-- Entidad: Usuario  →  tabla: usuarios
-- CHECK de correo: solo formato nombre.apellido@utec.edu.uy en minúsculas.
-- CHECK de cédula: exactamente 8 dígitos numéricos.
CREATE TABLE usuarios (
    id_usuario     SERIAL       PRIMARY KEY,
    cedula         VARCHAR(8)   NOT NULL UNIQUE,
    nombre         VARCHAR(50)  NOT NULL,
    apellido       VARCHAR(50)  NOT NULL,
    username       VARCHAR(50)  NOT NULL UNIQUE,
    password       VARCHAR(255) NOT NULL,
    correo         VARCHAR(100) NOT NULL UNIQUE,
    fec_nacimiento DATE         NOT NULL,
    est_activo     BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_cedula  CHECK (cedula  ~ '^[0-9]{8}$'),
    CONSTRAINT chk_correo  CHECK (correo  ~ '^[a-z]+\.[a-z]+@utec\.edu\.uy$')
);

-- Entidad: Rol  →  tabla: roles
CREATE TABLE roles (
    id_rol      SERIAL       PRIMARY KEY,
    nombre      VARCHAR(50)  NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    es_sistema  BOOLEAN      NOT NULL DEFAULT FALSE,
    est_activo  BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Entidad: Permiso  →  tabla: permisos
-- Los códigos siguen el patrón "entidad.accion" (ej. usuarios.leer).
CREATE TABLE permisos (
    id_permiso  SERIAL      PRIMARY KEY,
    codigo      VARCHAR(60) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

-- Entidad: InformeFinal  →  tabla: info_final
CREATE TABLE info_final (
    id_inf_final SERIAL   PRIMARY KEY,
    contenido    TEXT     NOT NULL,
    valoracion   INTEGER  NOT NULL,
    fec_creacion DATE     NOT NULL,
    est_activo   BOOLEAN  NOT NULL DEFAULT TRUE
);

-- Entidad: CategoriaInstancia  →  tabla: categorias_instancia
CREATE TABLE categorias_instancia (
    id_categoria_instancia SERIAL       PRIMARY KEY,
    nombre                 VARCHAR(100) NOT NULL,
    descripcion            VARCHAR(255),
    est_activo             BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Entidad: CategoriaRecordatorio  →  tabla: categorias_recordatorio
CREATE TABLE categorias_recordatorio (
    id_categoria_recordatorio SERIAL       PRIMARY KEY,
    nombre                    VARCHAR(100) NOT NULL,
    descripcion               VARCHAR(255),
    est_activo                BOOLEAN      NOT NULL DEFAULT TRUE
);


-- ============================================================
-- SECCIÓN 2 – Tablas que referencian la sección 1
-- ============================================================

-- Entidad: Direccion  →  tabla: direcciones
-- id_usuario es nullable: no toda dirección pertenece a un usuario
-- (las direcciones de ITR no tienen usuario asociado).
CREATE TABLE direcciones (
    id_direccion INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle        VARCHAR(100) NOT NULL,
    num_puerta   VARCHAR(10),
    num_apto     VARCHAR(10),
    id_ciudad    INTEGER      NOT NULL REFERENCES ciudades(id_ciudad),
    id_usuario   INTEGER      REFERENCES usuarios(id_usuario)
);

-- Entidad: RolPermiso  →  tabla: rol_permiso  (clave compuesta)
-- PK embebida: RolPermisoId { id_rol, id_permiso }
CREATE TABLE rol_permiso (
    id_rol     INTEGER NOT NULL REFERENCES roles(id_rol),
    id_permiso INTEGER NOT NULL REFERENCES permisos(id_permiso),
    PRIMARY KEY (id_rol, id_permiso)
);

-- Entidad: Funcionario  →  tabla: funcionarios
-- Especialización 1:1 de Usuario via @MapsId: la PK es también FK a usuarios.
CREATE TABLE funcionarios (
    id_usuario INTEGER NOT NULL PRIMARY KEY REFERENCES usuarios(id_usuario),
    est_activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Entidad: TeleUsuario  →  tabla: tele_usuario
CREATE TABLE tele_usuario (
    id_telefono SERIAL      PRIMARY KEY,
    numero      VARCHAR(20) NOT NULL,
    id_usuario  INTEGER     NOT NULL REFERENCES usuarios(id_usuario)
);

-- Entidad: Auditoria  →  tabla: auditoria
-- id_auditoria es Long en Java → BIGSERIAL.
-- detalle usa columnDefinition="jsonb" → tipo JSONB en PostgreSQL.
-- id_usuario nullable: los eventos de sistema no tienen usuario.
CREATE TABLE auditoria (
    id_auditoria BIGSERIAL   PRIMARY KEY,
    id_usuario   INTEGER     REFERENCES usuarios(id_usuario),
    accion       VARCHAR(50) NOT NULL,
    entidad      VARCHAR(50) NOT NULL,
    id_entidad   VARCHAR(50),
    fec_hora     TIMESTAMPTZ NOT NULL,
    detalle      JSONB
);


-- ============================================================
-- SECCIÓN 3 – Tablas que referencian la sección 2
-- ============================================================

-- Entidad: ITR  →  tabla: itr
-- Cada ITR tiene una dirección obligatoria.
CREATE TABLE itr (
    id_itr       SERIAL       PRIMARY KEY,
    codigo       VARCHAR(20)  NOT NULL UNIQUE,
    nombre       VARCHAR(100) NOT NULL,
    id_direccion INTEGER      NOT NULL REFERENCES direcciones(id_direccion),
    est_activo   BOOLEAN      NOT NULL DEFAULT TRUE
);


-- ============================================================
-- SECCIÓN 4 – Tablas que referencian la sección 3
-- ============================================================

-- Entidad: Carrera  →  tabla: carreras
-- Sin FK salientes (se incluye aquí para que grupos pueda referenciarla).
CREATE TABLE carreras (
    id_carrera SERIAL       PRIMARY KEY,
    codigo     VARCHAR(10)  NOT NULL UNIQUE,
    nombre     VARCHAR(100) NOT NULL,
    plan       VARCHAR(50)  NOT NULL,
    est_activo BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Entidad: Grupo  →  tabla: grupos
-- Representa un grupo académico: carrera + ITR + año + semestre.
CREATE TABLE grupos (
    id_grupo   SERIAL      PRIMARY KEY,
    nom_grupo  VARCHAR(50) NOT NULL,
    id_carrera INTEGER     NOT NULL REFERENCES carreras(id_carrera),
    id_itr     INTEGER     NOT NULL REFERENCES itr(id_itr),
    anio       INTEGER     NOT NULL,
    semestre   INTEGER     NOT NULL,
    est_activo BOOLEAN     NOT NULL DEFAULT TRUE
);

-- Entidad: TeleITR  →  tabla: tele_itr
CREATE TABLE tele_itr (
    id_telefono SERIAL      PRIMARY KEY,
    numero      VARCHAR(20) NOT NULL,
    id_itr      INTEGER     NOT NULL REFERENCES itr(id_itr)
);

-- Entidad: Pertenece  →  tabla: pertenece  (clave compuesta)
-- PK embebida: PerteneceId { id_carrera, id_itr }
-- Modela qué carreras se dictan en qué ITR.
CREATE TABLE pertenece (
    id_carrera INTEGER NOT NULL REFERENCES carreras(id_carrera),
    id_itr     INTEGER NOT NULL REFERENCES itr(id_itr),
    PRIMARY KEY (id_carrera, id_itr)
);


-- ============================================================
-- SECCIÓN 5 – Tablas que referencian la sección 4
-- ============================================================

-- Entidad: Estudiante  →  tabla: estudiantes
-- Especialización 1:1 de Usuario via @MapsId: la PK es también FK a usuarios.
CREATE TABLE estudiantes (
    id_usuario INTEGER NOT NULL PRIMARY KEY REFERENCES usuarios(id_usuario),
    id_grupo   INTEGER NOT NULL REFERENCES grupos(id_grupo),
    est_activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Entidad: Asignacion  →  tabla: asignaciones
-- Vincula un usuario a un rol con scope opcional (ITR, carrera o grupo).
-- Las FK de scope (id_itr, id_carrera, id_grupo) son nullable porque
-- el scope puede ser global, a nivel ITR, carrera o grupo.
CREATE TABLE asignaciones (
    id_asignacion SERIAL       PRIMARY KEY,
    id_usuario    INTEGER      NOT NULL REFERENCES usuarios(id_usuario),
    id_rol        INTEGER      NOT NULL REFERENCES roles(id_rol),
    id_itr        INTEGER      REFERENCES itr(id_itr),
    id_carrera    INTEGER      REFERENCES carreras(id_carrera),
    id_grupo      INTEGER      REFERENCES grupos(id_grupo),
    fec_creacion  TIMESTAMPTZ  NOT NULL,
    est_activo    BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Entidad: Instancia  →  tabla: instancias
-- Evento/reunión educativa creado por un funcionario.
-- id_categoria_instancia nullable: la instancia puede no tener categoría asignada.
CREATE TABLE instancias (
    id_instancia           SERIAL       PRIMARY KEY,
    titulo                 VARCHAR(100) NOT NULL,
    tipo                   VARCHAR(100) NOT NULL,
    fec_hora               TIMESTAMPTZ  NOT NULL,
    descripcion            VARCHAR(255) NOT NULL,
    est_activo             BOOLEAN      NOT NULL DEFAULT TRUE,
    id_funcionario         INTEGER      NOT NULL REFERENCES funcionarios(id_usuario),
    id_categoria_instancia INTEGER      REFERENCES categorias_instancia(id_categoria_instancia)
);


-- ============================================================
-- SECCIÓN 6 – Tablas que referencian la sección 5
-- ============================================================

-- Entidad: Incidencia  →  tabla: incidencias
-- Relación 1:1 con Instancia via @MapsId: la PK es también FK a instancias.
CREATE TABLE incidencias (
    id_instancia INTEGER      NOT NULL PRIMARY KEY REFERENCES instancias(id_instancia),
    lugar        VARCHAR(100) NOT NULL
);

-- Entidad: Seguimiento  →  tabla: seguimientos
-- Seguimiento educativo de un estudiante.
-- id_informe nullable: el informe se vincula al cerrar el seguimiento.
CREATE TABLE seguimientos (
    id_seguimiento SERIAL   PRIMARY KEY,
    id_informe     INTEGER  REFERENCES info_final(id_inf_final),
    id_estudiante  INTEGER  NOT NULL REFERENCES estudiantes(id_usuario),
    fec_inicio     DATE     NOT NULL,
    fec_cierre     DATE,
    est_activo     BOOLEAN  NOT NULL DEFAULT TRUE
);

-- Entidad: Observacion  →  tabla: observaciones
CREATE TABLE observaciones (
    id_observacion SERIAL       PRIMARY KEY,
    id_funcionario INTEGER      NOT NULL REFERENCES funcionarios(id_usuario),
    id_estudiante  INTEGER      NOT NULL REFERENCES estudiantes(id_usuario),
    titulo         VARCHAR(100) NOT NULL,
    contenido      TEXT         NOT NULL,
    fec_hora       TIMESTAMPTZ  NOT NULL,
    est_activo     BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Entidad: ArchivoAdjunto  →  tabla: arch_adjuntos
-- id_usuario: funcionario que sube el archivo.
-- id_estudiante: estudiante al que pertenece el archivo.
CREATE TABLE arch_adjuntos (
    id_archivo_adjunto SERIAL       PRIMARY KEY,
    id_usuario         INTEGER      NOT NULL REFERENCES usuarios(id_usuario),
    id_estudiante      INTEGER      NOT NULL REFERENCES estudiantes(id_usuario),
    ruta               VARCHAR(255) NOT NULL,
    categoria          VARCHAR(50)  NOT NULL,
    est_activo         BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Entidad: PartInstancia  →  tabla: part_instancia  (clave compuesta)
-- PK embebida: PartInstanciaId { id_participante, id_instancia }
-- Participantes de una instancia (usuarios en general, no solo funcionarios).
CREATE TABLE part_instancia (
    id_participante INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    id_instancia    INTEGER NOT NULL REFERENCES instancias(id_instancia),
    PRIMARY KEY (id_participante, id_instancia)
);

-- Entidad: Notificacion  →  tabla: notificaciones
CREATE TABLE notificaciones (
    id_notificacion SERIAL       PRIMARY KEY,
    id_instancia    INTEGER      NOT NULL REFERENCES instancias(id_instancia),
    asunto          VARCHAR(200) NOT NULL,
    mensaje         TEXT         NOT NULL,
    destinatario    VARCHAR(100) NOT NULL,
    fec_envio       DATE         NOT NULL,
    est_activo      BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Entidad: Recordatorio  →  tabla: recordatorios
-- recurrencia es un enum STRING: valores permitidos definidos en Recurrencia.java.
-- id_estudiante nullable: el recordatorio puede ser genérico (sin estudiante).
-- id_categoria nullable: la categoría es opcional.
CREATE TABLE recordatorios (
    id_recordatorio SERIAL       PRIMARY KEY,
    titulo          VARCHAR(100) NOT NULL,
    descripcion     VARCHAR(255),
    fec_hora        TIMESTAMPTZ  NOT NULL,
    recurrencia     VARCHAR(20)  NOT NULL DEFAULT 'NINGUNA',
    id_funcionario  INTEGER      NOT NULL REFERENCES funcionarios(id_usuario),
    id_estudiante   INTEGER      REFERENCES estudiantes(id_usuario),
    id_categoria    INTEGER      REFERENCES categorias_recordatorio(id_categoria_recordatorio),
    est_activo      BOOLEAN      NOT NULL DEFAULT TRUE,

    -- Protege contra valores de enum inválidos que Hibernate no puede rechazar en DB
    CONSTRAINT chk_recurrencia CHECK (recurrencia IN ('NINGUNA', 'DIARIA', 'SEMANAL', 'MENSUAL'))
);


-- ============================================================
-- SECCIÓN 7 – Tablas que referencian la sección 6
-- ============================================================

-- Entidad: InstanciaComun  →  tabla: inst_comun  (clave compuesta)
-- PK embebida: InstanciaComunId { id_instancia, id_seguimiento }
-- Vincula una instancia con un seguimiento (N:M entre instancias y seguimientos).
CREATE TABLE inst_comun (
    id_instancia   INTEGER NOT NULL REFERENCES instancias(id_instancia),
    id_seguimiento INTEGER NOT NULL REFERENCES seguimientos(id_seguimiento),
    PRIMARY KEY (id_instancia, id_seguimiento)
);

-- Entidad: PartSeguimiento  →  tabla: part_seguimientos  (clave compuesta)
-- PK embebida: PartSeguimientoId { id_participante, id_seguimiento }
-- Participantes de un seguimiento (funcionarios involucrados).
CREATE TABLE part_seguimientos (
    id_participante INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    id_seguimiento  INTEGER NOT NULL REFERENCES seguimientos(id_seguimiento),
    PRIMARY KEY (id_participante, id_seguimiento)
);

-- Entidad: Recibe  →  tabla: recibe  (clave compuesta)
-- PK embebida: RecibeId { id_notificacion, id_usuario }
-- Registro de qué usuarios reciben cada notificación.
CREATE TABLE recibe (
    id_notificacion INTEGER NOT NULL REFERENCES notificaciones(id_notificacion),
    id_usuario      INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    PRIMARY KEY (id_notificacion, id_usuario)
);

-- Entidad: EventoCalendario  →  tabla: eventos_calendario
-- Simula la integración con Google Calendar.
-- id_instancia y id_recordatorio son nullable: el evento puede originarse
-- desde una instancia, desde un recordatorio, o existir de forma independiente.
CREATE TABLE eventos_calendario (
    id_evento_calendario SERIAL       PRIMARY KEY,
    titulo               VARCHAR(200) NOT NULL,
    descripcion          TEXT,
    fec_inicio           TIMESTAMPTZ  NOT NULL,
    fec_fin              TIMESTAMPTZ,
    ubicacion            VARCHAR(255),
    id_instancia         INTEGER      REFERENCES instancias(id_instancia),
    id_recordatorio      INTEGER      REFERENCES recordatorios(id_recordatorio),
    google_event_id      VARCHAR(100) NOT NULL,
    google_calendar_link VARCHAR(500) NOT NULL,
    sincronizado         BOOLEAN      NOT NULL DEFAULT FALSE,
    est_activo           BOOLEAN      NOT NULL DEFAULT TRUE
);
